clusters acceptance tests
polar-rams/databricks-sdk-golang pull request #84
Opened 2021-05-20 09:28 UTC by siliang-j-1225

#54

2021-05-20 10:46 UTC, maniSbindra requested changes
Hi @siliang-j-1225, I have left a few suggestions.
Thanks,
Mani

2021-05-20 10:46 UTC, maniSbindra commented on tests/acceptance/azure/clusters_test.go
> +var clusterName = "acceptance_test_cluster_" + time.Now().String()
If the intent of using time.Now().String() is to get a unique suffix, then can  function ranSeq in the common test file be used instead ?
(https://github.com/polar-rams/databricks-sdk-golang/blob/f969885c86ab174704bcb673eb29efaa0c8edfff/tests/acceptance/azure/config_test.go#L36)

2021-05-20 10:46 UTC, maniSbindra commented on tests/acceptance/azure/clusters_test.go
> +}
Similar to above comment, there seems to be a strong dependency between TestAzureClustersRestart and TestAzureClustersAfterRestarting, and their execution order. Should the two functions be combined

2021-05-20 10:46 UTC, maniSbindra commented on tests/acceptance/azure/clusters_test.go
> +	for s == state {
Can this be combined to
```
for s := string(resp.State);  s == state ;{
```

2021-05-21 00:07 UTC, jsburckhardt reviewed
Please update the cluster delete option to remove completely the cluster.

2021-05-21 00:07 UTC, jsburckhardt commented on tests/acceptance/azure/clusters_test.go
> +	req := httpmodels.DeleteReq{
Please use ```PermanentDeleteReq``` to delete the cluster

2021-05-21 00:07 UTC, jsburckhardt commented on tests/acceptance/azure/clusters_test.go
> +	e := c.Clusters().Delete(req)
please use ```PermanentDelete``` to delete the cluster

2021-05-21 00:58 UTC, siliang-j-1225 commented on tests/acceptance/azure/clusters_test.go
> +var clusterName = "acceptance_test_cluster_" + time.Now().String()
updated to use randSeq in clusterName

2021-05-21 01:28 UTC, siliang-j-1225 commented on tests/acceptance/azure/clusters_test.go
> +}
combined TestAzureClustersEdit and TestAzureClustersAfterEdition to one function

2021-05-21 01:29 UTC, siliang-j-1225 commented on tests/acceptance/azure/clusters_test.go
> +}
same as above

2021-05-21 01:29 UTC, siliang-j-1225 commented on tests/acceptance/azure/clusters_test.go
> +}
combined

2021-05-21 01:30 UTC, siliang-j-1225 commented on azure/clusters/models/ClusterCloudProviderNodeInfo.go
> +	TotalCoreQuota     json.Number                      `json:"total_core_quota,omitempty" url:"total_core_quota,omitempty"`
updated to float32, same as ClusterCores. thanks for pointing out this!

2021-05-21 01:33 UTC, siliang-j-1225 commented on tests/acceptance/azure/clusters_test.go
> +	req := httpmodels.DeleteReq{
The `Delete` in clusters api is an alias for terminating. there is another test case of `PermanentDelete` executed at last  to delete the cluster

2021-05-21 01:33 UTC, siliang-j-1225 commented on tests/acceptance/azure/clusters_test.go
> +	e := c.Clusters().Delete(req)
as above

2021-05-21 01:33 UTC, siliang-j-1225 commented on tests/acceptance/azure/clusters_test.go
> +	for s == state {
done!

2021-05-21 01:40 UTC, siliang-j-1225 commented on tests/acceptance/azure/clusters_test.go
> +	assert.Equalf(t, string(resp.State), models.ClusterStateRunning, "TestAzureClustersAfterEdition: cluster is not running. State:%s", resp.State)
it is a little tricky here that we actually wait until the cluster state **is not** `models.ClusterStateRestarting`.
after edition, cluster will be in state of restarting. and the assertion is for checking the state next to restarting. 

The next state will be `models.ClusterStateRunning`, if everything works fine; Or it could be others (ClusterStateError, ClusterStateUnknown, ClusterStateTerminating), due to any error.

2021-05-21 02:54 UTC, maniSbindra submitted a review, later dismissed
lgtm. Thanks

2021-05-21 05:33 UTC, maniSbindra approved these changes

2021-05-21 05:34 UTC, merged